In [4]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [5]:
df = pd.read_csv("../data/raw_data/WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [6]:
df_copy = df.copy()

In [7]:
df_copy.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [8]:
df_copy.shape

(1470, 35)

In [9]:
df_copy.drop(columns=["EmployeeCount", "StandardHours", "EmployeeNumber"], inplace=True)
#EmployeeNumber is just an ID

In [7]:
df_copy.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'Over18',
       'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='str')

In [8]:
df_copy.shape

(1470, 32)

In [9]:
numeric_columns = df_copy.select_dtypes(include=["int","float"]).columns

In [10]:
catagorical_columns = df_copy.select_dtypes(include=["object"]).columns

C:\Users\Goutam\AppData\Local\Temp\ipykernel_8052\981779522.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  catagorical_columns = df_copy.select_dtypes(include=["object"]).columns

In [11]:
X = df_copy.drop("Attrition", axis=1)

In [12]:
X.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,94,...,3,1,0,8,0,1,6,4,0,5
1,49,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,61,...,4,4,1,10,3,3,10,7,1,7
2,37,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,92,...,3,2,0,7,3,3,0,0,0,0
3,33,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,56,...,3,3,0,8,3,3,8,7,3,0
4,27,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,40,...,3,4,1,6,3,3,2,2,2,2

In [13]:
y = df_copy["Attrition"]

In [14]:
y.head()

0    Yes
1     No
2    Yes
3     No
4     No
Name: Attrition, dtype: str

In [15]:
y = y.map({"Yes":1, "No":0})

In [16]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Attrition, dtype: int64

In [17]:
X.head()

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,94,...,3,1,0,8,0,1,6,4,0,5
1,49,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,61,...,4,4,1,10,3,3,10,7,1,7
2,37,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,92,...,3,2,0,7,3,3,0,0,0,0
3,33,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,56,...,3,3,0,8,3,3,8,7,3,0
4,27,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,40,...,3,4,1,6,3,3,2,2,2,2

In [18]:
X.shape

(1470, 31)

In [19]:
X = pd.get_dummies(X, drop_first=True, dtype=int)

In [20]:
X.shape

(1470, 44)

In [21]:
X.head()

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,41,1102,1,2,2,94,3,2,4,5993,...,0,0,0,0,0,1,0,0,1,1
1,49,279,8,1,3,61,2,2,2,5130,...,0,0,0,0,1,0,0,1,0,0
2,37,1373,2,2,4,92,2,1,3,2090,...,1,0,0,0,0,0,0,0,1,1
3,33,1392,3,4,4,56,3,1,3,2909,...,0,0,0,0,1,0,0,1,0,1
4,27,591,2,1,1,40,3,1,2,3468,...,1,0,0,0,0,0,0,1,0,0

In [22]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 44 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1470 non-null   int64
 1   DailyRate                          1470 non-null   int64
 2   DistanceFromHome                   1470 non-null   int64
 3   Education                          1470 non-null   int64
 4   EnvironmentSatisfaction            1470 non-null   int64
 5   HourlyRate                         1470 non-null   int64
 6   JobInvolvement                     1470 non-null   int64
 7   JobLevel                           1470 non-null   int64
 8   JobSatisfaction                    1470 non-null   int64
 9   MonthlyIncome                      1470 non-null   int64
 10  MonthlyRate                        1470 non-null   int64
 11  NumCompaniesWorked                 1470 non-null   int64
 12  PercentSalaryHike                  1470 non-null   int64
 13  PerformanceRating                  1470 non-null   int64
 14  RelationshipSatisfaction           1470 non-null   int64
 15  StockOptionLevel                   1470 non-null   int64
 16  TotalWorkingYears                  1470 non-null   int64
 17  TrainingTimesLastYear              1470 non-null   int64
 18  WorkLifeBalance                    1470 non-null   int64
 19  YearsAtCompany                     1470 non-null   int64
 20  YearsInCurrentRole                 1470 non-null   int64
 21  YearsSinceLastPromotion            1470 non-null   int64
 22  YearsWithCurrManager               1470 non-null   int64
 23  BusinessTravel_Travel_Frequently   1470 non-null   int64
 24  BusinessTravel_Travel_Rarely       1470 non-null   int64
 25  Department_Research & Development  1470 non-null   int64
 26  Department_Sales                   1470 non-null   int64
 27  EducationField_Life Sciences       1470 non-null   int64
 28  EducationField_Marketing           1470 non-null   int64
 29  EducationField_Medical             1470 non-null   int64
 30  EducationField_Other               1470 non-null   int64
 31  EducationField_Technical Degree    1470 non-null   int64
 32  Gender_Male                        1470 non-null   int64
 33  JobRole_Human Resources            1470 non-null   int64
 34  JobRole_Laboratory Technician      1470 non-null   int64
 35  JobRole_Manager                    1470 non-null   int64
 36  JobRole_Manufacturing Director     1470 non-null   int64
 37  JobRole_Research Director          1470 non-null   int64
 38  JobRole_Research Scientist         1470 non-null   int64
 39  JobRole_Sales Executive            1470 non-null   int64
 40  JobRole_Sales Representative       1470 non-null   int64
 41  MaritalStatus_Married              1470 non-null   int64
 42  MaritalStatus_Single               1470 non-null   int64
 43  OverTime_Yes                       1470 non-null   int64
dtypes: int64(44)
memory usage: 505.4 KB

##### We'll going  to scall only the continuous numeric columns...

In [23]:
binary_columns = []
for col in X.columns:
    if X[col].nunique()==2:
        binary_columns.append(col)

In [24]:
print(len(binary_columns))
binary_columns

22

['PerformanceRating',
 'BusinessTravel_Travel_Frequently',
 'BusinessTravel_Travel_Rarely',
 'Department_Research & Development',
 'Department_Sales',
 'EducationField_Life Sciences',
 'EducationField_Marketing',
 'EducationField_Medical',
 'EducationField_Other',
 'EducationField_Technical Degree',
 'Gender_Male',
 'JobRole_Human Resources',
 'JobRole_Laboratory Technician',
 'JobRole_Manager',
 'JobRole_Manufacturing Director',
 'JobRole_Research Director',
 'JobRole_Research Scientist',
 'JobRole_Sales Executive',
 'JobRole_Sales Representative',
 'MaritalStatus_Married',
 'MaritalStatus_Single',
 'OverTime_Yes']

In [25]:
continuous_columns = []
for col in X.columns:
    if col not in binary_columns:
        continuous_columns.append(col)

In [26]:
print(continuous_columns, len(continuous_columns), sep="\n")

['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']
22

In [27]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)

In [28]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((1102, 44), (368, 44), (1102,), (368,))

In [29]:
print(y.value_counts(normalize=True))

print(y_train.value_counts(normalize=True))

print(y_test.value_counts(normalize=True))

#the ratio is preserved because of stratify, and we should use stratify here because the dataset is imbalanced

Attrition
0    0.838776
1    0.161224
Name: proportion, dtype: float64
Attrition
0    0.838475
1    0.161525
Name: proportion, dtype: float64
Attrition
0    0.839674
1    0.160326
Name: proportion, dtype: float64

### Scalling

In [30]:
scaler = StandardScaler()

In [31]:
x_train[continuous_columns] = scaler.fit_transform(x_train[continuous_columns])

In [32]:
x_train.head()

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
22,-0.319271,-0.966810,-0.285354,1.068343,-1.577764,-0.605091,0.370808,0.859399,-0.641268,1.191983,...,0,0,0,1,0,0,0,0,1,0
74,-0.101078,-1.685283,-0.407522,0.097763,-0.656844,-0.506799,1.784752,-0.984919,1.159183,-0.749697,...,1,0,0,0,0,0,0,1,0,0
1339,-1.628429,-1.036905,-0.285354,-1.843398,1.184994,0.476116,0.370808,-0.984919,-0.641268,-0.872407,...,0,0,0,0,1,0,0,0,1,1
251,0.226212,-0.751519,-0.896194,1.068343,0.264075,-0.064487,0.370808,0.859399,0.258958,0.963040,...,0,0,0,0,0,0,0,0,1,0
1182,-0.101078,0.222300,-1.018362,1.068343,1.184994,-1.588006,-1.043137,-0.062760,0.258958,-0.460050,...,0,0,1,0,0,0,0,1,0,0

In [33]:
x_test[continuous_columns] = scaler.transform(x_test[continuous_columns])

In [34]:
x_test.head()

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
1307,-0.973850,1.030894,-1.018362,0.097763,0.264075,0.082950,0.370808,-0.984919,-1.541493,-0.629806,...,0,0,0,0,1,0,0,1,0,0
1190,-0.537464,0.430081,-0.896194,0.097763,1.184994,-0.998257,0.370808,-0.062760,-0.641268,-0.222434,...,0,0,0,0,1,0,0,0,0,0
1026,-0.537464,-0.511193,-0.285354,2.038923,1.184994,1.557324,0.370808,-0.062760,1.159183,0.587105,...,0,0,0,0,0,1,0,1,0,0
1212,-0.319271,-0.318432,1.180662,0.097763,-0.656844,-1.489715,-1.043137,-0.984919,1.159183,-0.773329,...,0,0,0,0,1,0,0,1,0,0
551,0.226212,-1.662752,-0.774026,0.097763,0.264075,-1.047403,1.784752,-0.062760,-0.641268,-0.023193,...,0,0,0,0,0,0,0,1,0,0

In [35]:
x_train[continuous_columns].describe()

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PercentSalaryHike,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1.102000e+03,1.102000e+03,1.102000e+03,1.102000e+03,1.102000e+03,1.102000e+03,1.102000e+03,1.102000e+03,1.102000e+03,1.102000e+03,...,1.102000e+03,1.102000e+03,1.102000e+03,1.102000e+03,1.102000e+03,1.102000e+03,1.102000e+03,1.102000e+03,1.102000e+03,1.102000e+03
mean,-1.611939e-17,-8.059695e-17,3.546266e-17,1.079999e-16,-7.414920e-17,3.288356e-16,-4.916414e-17,-1.362089e-16,-9.026859e-17,9.752231e-17,...,9.994022e-17,-2.256715e-17,2.256715e-17,-4.835817e-17,-3.223878e-17,1.611939e-17,7.898501e-17,8.220889e-17,-1.934327e-17,-1.096119e-16
std,1.000454e+00,1.000454e+00,1.000454e+00,1.000454e+00,1.000454e+00,1.000454e+00,1.000454e+00,1.000454e+00,1.000454e+00,1.000454e+00,...,1.000454e+00,1.000454e+00,1.000454e+00,1.000454e+00,1.000454e+00,1.000454e+00,1.000454e+00,1.000454e+00,1.000454e+00,1.000454e+00
min,-2.064815e+00,-1.757881e+00,-1.018362e+00,-1.843398e+00,-1.577764e+00,-1.735444e+00,-2.457082e+00,-9.849193e-01,-1.541493e+00,-1.189589e+00,...,-1.151606e+00,-1.616103e+00,-9.272842e-01,-1.453861e+00,-2.202509e+00,-2.459584e+00,-1.156655e+00,-1.170867e+00,-6.804786e-01,-1.168997e+00
25%,-7.556569e-01,-8.416408e-01,-8.961941e-01,-8.728175e-01,-6.568445e-01,-8.508195e-01,-1.043137e+00,-9.849193e-01,-6.412677e-01,-7.700768e-01,...,-8.787464e-01,-6.942887e-01,-9.272842e-01,-6.796864e-01,-5.983021e-01,-1.063878e+00,-6.573860e-01,-6.125394e-01,-6.804786e-01,-6.037340e-01
50%,-1.556259e-01,-8.012208e-03,-2.853542e-01,9.776261e-02,2.640749e-01,3.380445e-02,3.708076e-01,-6.276036e-02,2.589578e-01,-3.269331e-01,...,-3.330273e-01,2.275259e-01,2.527010e-01,-1.635697e-01,2.038012e-01,3.318285e-01,-3.245400e-01,-3.333754e-01,-3.707358e-01,-3.211024e-01
75%,6.625982e-01,8.725549e-01,6.614476e-01,1.068343e+00,1.184994e+00,8.692827e-01,3.708076e-01,8.593986e-01,1.159183e+00,3.997339e-01,...,7.584109e-01,1.149341e+00,2.527010e-01,4.815763e-01,2.038012e-01,3.318285e-01,3.411521e-01,7.832803e-01,2.487499e-01,8.094242e-01
max,2.517239e+00,1.736850e+00,2.402341e+00,2.038923e+00,1.184994e+00,1.704761e+00,1.784752e+00,2.703716e+00,1.159183e+00,2.921849e+00,...,2.668428e+00,1.149341e+00,2.612671e+00,3.707306e+00,2.610111e+00,1.727535e+00,5.000996e+00,3.574919e+00,3.965664e+00,3.635741e+00

In [39]:
x_train.to_csv("../data/processed_data/x_train.csv", index=False)
x_test.to_csv("../data/processed_data/x_test.csv", index=False)
y_train.to_csv("../data/processed_data/y_train.csv", index=False)
y_test.to_csv("../data/processed_data/y_test.csv", index=False)